x-default-environment: &default-environment
  TZ: "UTC"
  NODE_ENV: development
  MYSQL_HOST: db
  MYSQL_USERNAME: root
  MYSQL_DATABASE: student_sundial_development
  MYSQL_PASSWORD: &default-db-password DevPwd99!
  MYSQL_PORT: &default-db-port 3306
  MYSQL_HEALTH_CHECK_INTERVAL_SECONDS: 5
  MYSQL_HEALTH_CHECK_TIMEOUT_SECONDS: 10
  MYSQL_HEALTH_CHECK_RETRIES: 3
  MYSQL_HEALTH_CHECK_START_PERIOD_SECONDS: 5
  FRONTEND_URL: "http://localhost:8080"
  VITE_APPLICATION_NAME: "Student Sundial"
  VITE_API_BASE_URL: "http://localhost:3000"
  VITE_AUTH0_CLIENT_ID: "TmJtOIRuRHC841MqXZZDJ2vBQJ8AgdCl"
  VITE_AUTH0_AUDIENCE: "testing"
  VITE_AUTH0_DOMAIN: "https://dev-rzjcjlzhy63wjf31.us.auth0.com"
  RELEASE_TAG: "${RELEASE_TAG:-development}"
  GIT_COMMIT_HASH: "${GIT_COMMIT_HASH:-not-set}"
  MAIL_HOST: "mail"
  MAIL_PORT: 1025
  MAIL_FROM: "student-sundial.development@viu.ca"
  MAIL_SERVICE: "MailDev"

services:
  api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
    env_file:
      - ./api/.env.development
    environment:
      <<: *default-environment
    tty: true # allows attaching debugger, equivalent of docker exec -t
    # stdin_open: true # equivalent of docker exec -i
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/api
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      - db
      #- mail

  web:
    build:
      context: ./web
      dockerfile: development.Dockerfile
    environment:
      <<: *default-environment
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/web
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      - api

  # test_api:
  #   build:
  #     context: ./api
  #     dockerfile: development.Dockerfile
  #   command: /bin/true
  #   env_file:
  #     - ./api/.env.development
  #   environment:
  #     <<: *default-environment
  #     NODE_ENV: test
  #     DB_DATABASE: student_sundial_test
  #     DEFAULT_LOG_LEVEL: "info"
  #     DB_HEALTH_CHECK_START_PERIOD_SECONDS: 0
  #   tty: true
  #   volumes:
  #     - ./api:/usr/src/api
  #   depends_on:
  #     - db
  #     - mail

  # test_web:
  #   build:
  #     context: ./web
  #     dockerfile: development.Dockerfile
  #   command: /bin/true
  #   environment:
  #     <<: *default-environment
  #     NODE_ENV: test
  #   tty: true
  #   volumes:
  #     - ./web:/usr/src/web

  db:
    image: mariadb:10.1
    user: root
    environment:
      <<: *default-environment
      DB_HOST: "localhost"
      MYSQL_ROOT_PASSWORD: *default-db-password
      TZ: "America/Vancouver"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # mail:
  #   image: maildev/maildev
  #   user: root
  #   ports:
  #     - "1080:1080" # Web UI
  #     - "1025:1025" # SMTP

  # For easily generating large PlantUML diagrams
  # Not relevant to production environment.
  # Accessible at http://localhost:9999
  # plantuml:
  #   image: plantuml/plantuml-server:jetty
  #   ports:
  #     - 9999:8080
  #   environment:
  #     PLANTUML_LIMIT_SIZE: 8192

volumes:
  db_data: