name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v5.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: "v"
        tag_template: "yyyy.mm.dd.i"

    - name: Extract Git Commit Hash
      id: git_commit_hash
      run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Ensure build script
      run: chmod +x ./bin/build.sh
      
    - name: Ensure package build script
      run: chmod +x ./bin/package-build.sh

    - name: Run build script
      run: ./bin/build.sh

    - name: Packaging build
      run: ./bin/package-build.sh

    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./student-sundial-app.tar.gz
        asset_name: student-sundial-app.tar.gz
        asset_content_type: application/gzip

